SP500 = [
    'AAPL', 'ABBV', 'ABT', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'AEE',
    'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK',
    'ALL', 'ALLE', 'AMAT', 'AMCR', 'AMD', 'AME', 'AMGN', 'AMP', 'AMT', 'AMZN',
    'ANET', 'ANSS', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APTV', 'ARE', 'ATO',
    'ATVI', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXP', 'AZO', 'BA', 'BAC', 'BAX',
    'BBWI', 'BBY', 'BDX', 'BEN', 'BF-B', 'BIIB', 'BIO', 'BK', 'BKNG', 'BKR',
    'BLK', 'BMY', 'BR', 'BRK-B', 'BRO', 'BSX', 'BWA', 'BXP', 'C', 'CAG',
    'CAH', 'CARR', 'CAT', 'CB', 'CBOE', 'CBRE', 'CCI', 'CCL', 'CDAY', 'CDNS',
    'CDW', 'CE', 'CEG', 'CF', 'CFG', 'CHD', 'CHRW', 'CHTR', 'CI', 'CINF',
    'CL', 'CLX', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP',
    'COF', 'COO', 'COP', 'COST', 'CPB', 'CPRT', 'CPT', 'CRL', 'CRM', 'CSCO',
    'CSGP', 'CSX', 'CTAS', 'CTLT', 'CTRA', 'CTSH', 'CTVA', 'CVS', 'CVX', 'CZR',
    'D', 'DAL', 'DD', 'DE', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS',
    'DISH', 'DLR', 'DLTR', 'DOV', 'DOW', 'DPZ', 'DRI', 'DTE', 'DUK', 'DVA',
    'DVN', 'DXC', 'DXCM', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EIX', 'EL',
    'EMN', 'EMR', 'ENPH', 'EOG', 'EPAM', 'EQIX', 'EQR', 'EQT', 'ES', 'ESS',
    'ETN', 'ETR', 'ETSY', 'EVRG', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'F',
    'FANG', 'FAST', 'FBHS', 'FCX', 'FDS', 'FDX', 'FE', 'FFIV', 'FIS', 'FISV',
    'FITB', 'FLT', 'FMC', 'FOX', 'FOXA', 'FRC', 'FRT', 'FTNT', 'FTV', 'GD',
    'GE', 'GILD', 'GIS', 'GL', 'GLW', 'GM', 'GNRC', 'GOOG', 'GOOGL', 'GPC',
    'GPN', 'GRMN', 'GS', 'GWW', 'HAL', 'HAS', 'HBAN', 'HCA', 'HD', 'HOLX',
    'HON', 'HPE', 'HPQ', 'HRL', 'HSIC', 'HST', 'HSY', 'HUM', 'HWM', 'IBM',
    'ICE', 'IDXX', 'IEX', 'IFF', 'ILMN', 'INCY', 'INTC', 'INTU', 'INVH', 'IP',
    'IPG', 'IQV', 'IR', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT',
    'JCI', 'JKHY', 'JNJ', 'JNPR', 'JPM', 'K', 'KDP', 'KEY', 'KEYS', 'KHC',
    'KIM', 'KLAC', 'KMB', 'KMI', 'KMX', 'KO', 'KR', 'L', 'LDOS', 'LEN',
    'LH', 'LHX', 'LIN', 'LKQ', 'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LRCX',
    'LUMN', 'LUV', 'LVS', 'LW', 'LYB', 'LYV', 'MA', 'MAA', 'MAR', 'MAS',
    'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'META', 'MGM', 'MHK',
    'MKC', 'MKTX', 'MLM', 'MMC', 'MMM', 'MNST', 'MO', 'MOH', 'MOS', 'MPC',
    'MPWR', 'MRK', 'MRNA', 'MRO', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTCH',
    'MTD', 'MU', 'NCLH', 'NDAQ', 'NDSN', 'NEE', 'NEM', 'NFLX', 'NI', 'NKE',
    'NOC', 'NOW', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWL',
    'NWS', 'NWSA', 'NXPI', 'O', 'ODFL', 'OGN', 'OKE', 'OMC', 'ON', 'ORCL',
    'ORLY', 'OTIS', 'OXY', 'PARA', 'PAYC', 'PAYX', 'PCAR', 'PCG', 'PEAK', 'PEG',
    'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PKI', 'PLD',
    'PM', 'PNC', 'PNR', 'PNW', 'POOL', 'PPG', 'PPL', 'PRU', 'PSA', 'PSX',
    'PTC', 'PVH', 'PWR', 'PXD', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'RE', 'REG',
    'REGN', 'RF', 'RHI', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST',
    'RSG', 'RTX', 'SBAC', 'SBNY', 'SBUX', 'SCHW', 'SEE', 'SHW', 'SIVB', 'SJM',
    'SLB', 'SNA', 'SNPS', 'SO', 'SPG', 'SPGI', 'SRE', 'STE', 'STT', 'STX',
    'STZ', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TDG', 'TDY',
    'TECH', 'TEL', 'TER', 'TFC', 'TFX', 'TGT', 'TJX', 'TMO', 'TMUS', 'TPR',
    'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTWO', 'TXN',
    'TXT', 'TYL', 'UAL', 'UDR', 'UHS', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI',
    'USB', 'V', 'VFC', 'VICI', 'VLO', 'VMC', 'VNO', 'VRSK', 'VRSN', 'VRTX',
    'VTR', 'VTRS', 'VZ', 'WAB', 'WAT', 'WBA', 'WBD', 'WDC', 'WEC', 'WELL',
    'WFC', 'WHR', 'WM', 'WMB', 'WMT', 'WRB', 'WRK', 'WST', 'WTW', 'WY',
    'WYNN', 'XEL', 'XOM', 'XRAY', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZION', 'ZTS',
]

ADDITIONAL_STOCKS = [
    'ABNB', 'ACGL', 'ACM', 'ACHC', 'ACIW', 'ACLS', 'ACU', 'AGCO', 'AGNC', 'AIT',
    'AL', 'ALNY', 'ALSN', 'AM', 'AMED', 'AMKR', 'AMSF', 'AN', 'ANF', 'ANGO',
    'ANN', 'AORT', 'APG', 'APPF', 'APPS', 'AR', 'ARES', 'ARKO', 'ARMK', 'AROC',
    'ARVN', 'ASB', 'ASH', 'ASTE', 'ATI', 'ATKR', 'ATMU', 'AUR', 'AUY', 'AVNT',
    'AXON', 'AZEK', 'AZZ', 'BALL', 'BANF', 'BC', 'BCPC', 'BDC', 'BECN', 'BGNE',
    'BHC', 'BJ', 'BKNG', 'BKU', 'BLDR', 'BNL', 'BOH', 'BOOT', 'BRC', 'BRZE',
    'BSIG', 'BTU', 'BURL', 'BW', 'BWE', 'BWXT', 'BYD', 'BYRN', 'CADE', 'CALM',
    'CARG', 'CARS', 'CASY', 'CBSH', 'CC', 'CCCS', 'CEIX', 'CENX', 'CG', 'CGNX',
    'CHEF', 'CHE', 'CHH', 'CHRD', 'CHWY', 'CIFR', 'CIR', 'CIVI', 'CLBK', 'CLH',
    'CLOS', 'CLS', 'CLVT', 'CMBM', 'CMC', 'CMD', 'CNH', 'CNK', 'CNM', 'CNMD',
    'CNNE', 'CNO', 'CNXC', 'COHR', 'COLB', 'COOP', 'CORT', 'CPK', 'CPRX', 'CRC',
    'CRI', 'CRK', 'CROX', 'CRUS', 'CSL', 'CSWI', 'CTO', 'CUBE', 'CUBI', 'CUZ',
    'CVBF', 'CVCO', 'CVLT', 'CW', 'CWST', 'CWK', 'CXT', 'CYBR', 'DASH', 'DAR',
    'DBRG', 'DECK', 'DEN', 'DINO', 'DIOD', 'DKS', 'DOCN', 'DOCS', 'DOCU', 'DOX',
    'DSGX', 'DT', 'DTM', 'DUOL', 'DV', 'DVAX', 'DXPE', 'DY', 'EAT', 'EFSC',
    'EHC', 'ELAN', 'ELF', 'ENIC', 'ENOV', 'ENR', 'ENVX', 'EPRT', 'EQC', 'ERJ',
    'ESAB', 'ESI', 'ESNT', 'ESTC', 'EVR', 'EVTC', 'EWBC', 'EXAS', 'EXEL', 'EXPO',
    'EYE', 'EZPW', 'FAF', 'FATE', 'FBIN', 'FELE', 'FIVE', 'FIVN', 'FIX', 'FL',
    'FLEX', 'FLO', 'FLS', 'FLYW', 'FN', 'FNB', 'FND', 'FOLD', 'FORM', 'FOUR',
    'FOXF', 'FROG', 'FSS', 'FSTR', 'FTDR', 'FULT', 'G', 'GATX', 'GBCI', 'GEO',
    'GEOS', 'GFL', 'GGG', 'GH', 'GHC', 'GLOB', 'GLPI', 'GMED', 'GNTX', 'GO',
    'GOOG', 'GRAB', 'GXO', 'HAYW', 'HBI', 'HEES', 'HELE', 'HGV', 'HIG', 'HIMS',
    'HLI', 'HLX', 'HNI', 'HOMB', 'HP', 'HQY', 'HRB', 'HRI', 'HUBG', 'HUBB',
    'HUBS', 'HUN', 'HYPR', 'IAC', 'IBKR', 'IBP', 'ICLR', 'ICUI', 'IDA', 'IDCC',
    'IESC', 'IGMS', 'IMVT', 'INDB', 'INGR', 'INTA', 'IOSP', 'IONS', 'IPAR', 'IPGP',
    'IRTC', 'ITCI', 'ITGR', 'ITT', 'JACK', 'JAMF', 'JBL', 'JEF', 'JELD', 'JFIN',
    'JHG', 'JLL', 'JNPR', 'JOBY', 'KALU', 'KBH', 'KBR', 'KELYA', 'KFY', 'KGS',
    'KMPR', 'KN', 'KNSL', 'KNX', 'KRC', 'KRG', 'KSS', 'KTB', 'KVUE', 'KYMR',
    'LANC', 'LAUR', 'LAZ', 'LBRT', 'LEA', 'LFST', 'LGIH', 'LH', 'LITE', 'LIVN',
    'LKFN', 'LLYVK', 'LNTH', 'LPLA', 'LPX', 'LSCC', 'LSTR', 'LULU', 'LZB', 'M',
    'MATV', 'MASI', 'MATX', 'MAX', 'MAXI', 'MBC', 'MBUU', 'MC', 'MCW', 'MDGL',
    'MDXG', 'MEC', 'MEDP', 'MELI', 'MEOH', 'MGEE', 'MGNI', 'MGRC', 'MHO', 'MIDD',
    'MIR', 'MKSI', 'MLI', 'MMSI', 'MOD', 'MODV', 'MORN', 'MOV', 'MP', 'MPAA',
    'MPW', 'MRCY', 'MRVL', 'MSGE', 'MSGS', 'MSM', 'MSTR', 'MTDR', 'MTRN', 'MTSI',
    'MTX', 'MUR', 'MUSA', 'MVST', 'MXCT', 'NABL', 'NBHC', 'NBTB', 'NEO', 'NEOG',
    'NET', 'NGD', 'NGVT', 'NHI', 'NJR', 'NLY', 'NNN', 'NOA', 'NOG', 'NOV',
    'NR', 'NSP', 'NTCT', 'NTRA', 'NU', 'NUVB', 'NVAX', 'NVEE', 'NVT', 'NYCB',
    'OFLX', 'OGE', 'OHI', 'OI', 'OIS', 'OLN', 'OMCL', 'ONB', 'ONTO', 'OPEN',
    'OPK', 'ORA', 'OSIS', 'OSK', 'OTTR', 'OUST', 'OUT', 'OVV', 'PAGS', 'PAR',
    'PATK', 'PAYC', 'PCOR', 'PCTY', 'PCVX', 'PDCO', 'PDFS', 'PECO', 'PEN', 'PENN',
    'PGC', 'PII', 'PINC', 'PIPR', 'PLNT', 'PLXS', 'PNFP', 'POR', 'POST', 'POWL',
    'PRFT', 'PRGO', 'PRHD', 'PRI', 'PRIM', 'PRK', 'PRKS', 'PRLB', 'PROF', 'PSTG',
    'PTC', 'PTCT', 'PTGX', 'PVH', 'PWSC', 'QLYS', 'QNST', 'R', 'RAMP', 'RBA',
    'RBLX', 'RDN', 'RDNT', 'REZI', 'RGA', 'RGEN', 'RGLD', 'RH', 'RHI', 'RIOT',
    'RIVN', 'RKT', 'RMBS', 'RNG', 'ROKU', 'RPD', 'RPM', 'RVMD', 'RYAM', 'RYDE',
    'SAH', 'SAIL', 'SAM', 'SAIA', 'SANM', 'SCI', 'SE', 'SEDG', 'SFBS', 'SHAK',
    'SHOP', 'SHOO', 'SI', 'SIGI', 'SITC', 'SITE', 'SLAB', 'SLG', 'SM', 'SMAR',
    'SMCI', 'SMPX', 'SN', 'SNAP', 'SND', 'SNOW', 'SNV', 'SON', 'SONO', 'SP',
    'SPOT', 'SQ', 'SRCL', 'SSNC', 'ST', 'STAA', 'STAG', 'STER', 'STLD', 'STNE',
    'STRA', 'SUI', 'SUN', 'SWI', 'SWN', 'SYBT', 'SYNA', 'TASK', 'TCBI', 'TDC',
    'TDS', 'TENB', 'TFSL', 'THS', 'TKR', 'TMHC', 'TNET', 'TNL', 'TOL', 'TOST',
    'TREX', 'TRIP', 'TTC', 'TTD', 'TTMI', 'TW', 'TWLO', 'TWOU', 'TXG', 'TXRH',
    'U', 'UBSI', 'UCBI', 'UDMY', 'UFI', 'UFPI', 'UGI', 'UHAL', 'UI', 'UMBF',
    'UPBD', 'UPST', 'URBN', 'USAC', 'USFD', 'USM', 'VCTR', 'VEEV', 'VEL', 'VERX',
    'VG', 'VIAV', 'VICR', 'VIR', 'VIRT', 'VNDA', 'VNET', 'VRNS', 'VSH', 'VSEC',
    'VSTO', 'VTLE', 'VTOL', 'W', 'WBMD', 'WDFC', 'WEN', 'WFRD', 'WGO', 'WH',
    'WING', 'WIRE', 'WK', 'WKME', 'WLK', 'WOLF', 'WPC', 'WRAP', 'WSC', 'WSM',
    'WTFC', 'WTS', 'WU', 'WWD', 'X', 'XNCR', 'XP', 'XPEL', 'XPER', 'XPO',
    'XPOF', 'XRAY', 'YELP', 'YEXT', 'YOU', 'Z', 'ZD', 'ZETA', 'ZG', 'ZI',
    'ZM', 'ZS', 'ZWS',
]

STOCK_UNIVERSE = list(dict.fromkeys(SP500 + ADDITIONAL_STOCKS))

SECTOR_MAP = {
    'Technology': [
        'AAPL', 'MSFT', 'GOOGL', 'GOOG', 'NVDA', 'META', 'ADBE', 'CRM', 'CSCO', 'ORCL',
        'ACN', 'TXN', 'QCOM', 'INTC', 'AMD', 'AVGO', 'NOW', 'INTU', 'AMAT', 'ADI',
        'CDNS', 'SNPS', 'KLAC', 'LRCX', 'MCHP', 'NXPI', 'FTNT', 'ANSS', 'KEYS', 'CDW',
        'SWKS', 'ON', 'MPWR', 'TER', 'FFIV', 'JNPR', 'AKAM', 'IT', 'EPAM', 'CSGP',
        'CTSH', 'DXC', 'HPE', 'HPQ', 'IBM', 'STX', 'WDC', 'NTAP', 'MSI', 'TYL',
        'BR', 'JKHY', 'FISV', 'FIS', 'GPN', 'PYPL', 'ADSK', 'PTC', 'CYBR', 'NET',
        'SNOW', 'ZS', 'CRWD', 'DOCN', 'ESTC', 'MU', 'MRVL', 'SMCI', 'HUBS', 'TWLO',
        'DOCU', 'ZM', 'SPOT', 'SQ', 'SHOP', 'RBLX', 'SNAP', 'U', 'TTD', 'ROKU',
        'SMAR', 'VEEV', 'COHR', 'IPGP', 'MKSI', 'CGNX', 'DIOD', 'SLAB', 'LSCC',
        'SYNA', 'ACLS', 'ONTO', 'FORM', 'PSTG', 'DT', 'FROG', 'QLYS', 'TENB',
        'VRNS', 'APPF', 'JAMF', 'PCTY', 'PAYC', 'PCOR', 'ZI', 'DUOL', 'MSTR',
    ],
    'Consumer Discretionary': [
        'AMZN', 'TSLA', 'HD', 'NKE', 'MCD', 'LOW', 'SBUX', 'DIS', 'NFLX', 'TJX',
        'BKNG', 'CMG', 'MAR', 'ORLY', 'AZO', 'ROST', 'DHI', 'LEN', 'PHM', 'NVR',
        'APTV', 'BWA', 'GM', 'F', 'CCL', 'RCL', 'NCLH', 'WYNN', 'LVS', 'MGM',
        'CZR', 'DPZ', 'DRI', 'YUM', 'ETSY', 'EBAY', 'BBY', 'KMX', 'TSCO', 'ULTA',
        'POOL', 'DG', 'DLTR', 'CHWY', 'W', 'DECK', 'CROX', 'LULU', 'RL', 'PVH',
        'TPR', 'HAS', 'TTWO', 'EA', 'MTCH', 'LYV', 'HGV', 'SHAK', 'WING', 'TXRH',
        'EAT', 'JACK', 'DKS', 'FIVE', 'BOOT', 'FL', 'ANF', 'URBN', 'BJ', 'CASY',
        'GPC', 'LKQ', 'GRMN', 'LGIH', 'TOL', 'KBH', 'MHO', 'RH', 'WSM', 'BURL',
        'DASH', 'ABNB', 'GRAB', 'RIVN',
    ],
    'Healthcare': [
        'JNJ', 'UNH', 'PFE', 'TMO', 'ABT', 'MRK', 'LLY', 'ABBV', 'GILD', 'ISRG',
        'BMY', 'AMGN', 'MDT', 'SYK', 'BSX', 'EW', 'DHR', 'BDX', 'ZBH', 'BAX',
        'CI', 'HUM', 'CNC', 'MOH', 'HCA', 'DVA', 'UHS', 'HOLX', 'DXCM', 'IDXX',
        'IQV', 'CRL', 'PKI', 'TECH', 'BIO', 'ILMN', 'ALGN', 'RMD', 'TFX', 'STE',
        'BIIB', 'REGN', 'VRTX', 'MRNA', 'INCY', 'ALNY', 'COO', 'HSIC', 'MCK',
        'CAH', 'DGX', 'LH', 'WST', 'MTD', 'WAT', 'XRAY', 'VTRS', 'OGN',
        'ICLR', 'MEDP', 'EXAS', 'IRTC', 'MASI', 'MMSI', 'GMED', 'ANGO', 'ACHC',
        'EHC', 'ENOV', 'LIVN', 'NVAX', 'DVAX', 'EXEL', 'ITCI', 'BGNE',
    ],
    'Financial Services': [
        'JPM', 'V', 'MA', 'BRK-B', 'MS', 'GS', 'BLK', 'BAC', 'WFC', 'C',
        'SCHW', 'AXP', 'USB', 'PNC', 'TFC', 'COF', 'DFS', 'CFG', 'KEY', 'FITB',
        'MTB', 'HBAN', 'CMA', 'ZION', 'RF', 'STT', 'BK', 'NTRS', 'AMP', 'RJF',
        'CME', 'ICE', 'CBOE', 'NDAQ', 'MSCI', 'SPGI', 'MCO', 'FDS', 'MKTX',
        'MMC', 'AON', 'AJG', 'WTW', 'BRO', 'AIG', 'ALL', 'PGR', 'TRV', 'CB',
        'CINF', 'GL', 'AFL', 'MET', 'PRU', 'LNC', 'L', 'AIZ', 'RE', 'WRB',
        'BEN', 'IVZ', 'TROW', 'SYF', 'FLT', 'GPN', 'IBKR', 'LPLA', 'EVR', 'JEF',
        'LAZ', 'PIPR', 'PFG', 'RGA', 'AGNC', 'NLY', 'ARES', 'CG', 'KKR',
        'COOP', 'RKT', 'ESNT', 'RDN', 'KNSL', 'HIG', 'SIGI',
    ],
    'Consumer Staples': [
        'PG', 'KO', 'PEP', 'COST', 'WMT', 'MDLZ', 'CL', 'KMB', 'GIS', 'K',
        'SJM', 'CAG', 'CPB', 'HRL', 'HSY', 'MKC', 'CHD', 'CLX', 'EL', 'KHC',
        'KDP', 'MNST', 'STZ', 'MO', 'PM', 'TAP', 'BF-B', 'TSN', 'KR', 'SYY',
        'ADM', 'WBA', 'USFD', 'SAM', 'POST', 'INGR', 'LANC', 'CALM', 'FLO', 'KVUE',
    ],
    'Energy': [
        'CVX', 'XOM', 'COP', 'EOG', 'SLB', 'MPC', 'PSX', 'VLO', 'OXY', 'DVN',
        'HAL', 'BKR', 'PXD', 'FANG', 'EQT', 'MRO', 'APA', 'CTRA', 'OKE', 'WMB',
        'KMI', 'TRGP', 'AM', 'OVV', 'NOV', 'SM', 'AR', 'SWN', 'CRC', 'CHRD',
        'DINO', 'LBRT', 'BTU', 'CEIX', 'MUR', 'NOG', 'MTDR', 'VTLE', 'CRK',
    ],
    'Industrial': [
        'BA', 'CAT', 'GE', 'MMM', 'RTX', 'DE', 'UPS', 'HON', 'UNP', 'CSX',
        'NSC', 'FDX', 'LMT', 'NOC', 'GD', 'LHX', 'TDG', 'HWM', 'TXT', 'OTIS',
        'CARR', 'ETN', 'EMR', 'ITW', 'PH', 'ROK', 'DOV', 'IR', 'CMI', 'SNA',
        'SWK', 'FAST', 'GWW', 'ODFL', 'JBHT', 'CHRW', 'EXPD', 'DAL', 'UAL', 'LUV',
        'ALK', 'WAB', 'TT', 'ALLE', 'AOS', 'FTV', 'GNRC', 'PWR', 'PCAR', 'NDSN',
        'IEX', 'AME', 'ROP', 'RSG', 'WM', 'VRSK', 'URI', 'J', 'LDOS', 'KBR',
        'JCI', 'TRMB', 'CTAS', 'CPRT', 'FLT', 'FBHS', 'MAS', 'MLM', 'VMC', 'NUE',
        'STLD', 'FCX', 'CLH', 'XPO', 'GXO', 'SAIA', 'BLDR', 'ATKR', 'WCC',
        'OSK', 'AGCO', 'TTC', 'TREX', 'AZEK',
    ],
    'Utilities': [
        'NEE', 'DUK', 'SO', 'D', 'AEP', 'EXC', 'SRE', 'ED', 'PEG', 'EIX',
        'WEC', 'DTE', 'ES', 'AEE', 'CMS', 'CNP', 'ETR', 'FE', 'PPL', 'EVRG',
        'AES', 'NI', 'PNW', 'LNT', 'NRG', 'AWK', 'ATO', 'PCG', 'CEG', 'ENPH',
        'OGE', 'POR', 'NJR', 'IDA', 'UGI', 'MGEE',
    ],
    'Real Estate': [
        'AMT', 'PLD', 'CCI', 'EQIX', 'SPG', 'O', 'PSA', 'DLR', 'WELL', 'AVB',
        'EQR', 'ESS', 'MAA', 'UDR', 'CPT', 'INVH', 'SBAC', 'ARE', 'BXP', 'VNO',
        'SLG', 'KIM', 'REG', 'FRT', 'HST', 'VICI', 'GLPI', 'VTR', 'PEAK', 'MPW',
        'NHI', 'OHI', 'EXR', 'IRM', 'KRC', 'SUI', 'CUBE', 'NNN', 'STAG',
    ],
    'Materials': [
        'LIN', 'APD', 'SHW', 'ECL', 'DD', 'EMN', 'PPG', 'NEM', 'CF', 'MOS',
        'ALB', 'FMC', 'IFF', 'CE', 'AVY', 'SEE', 'PKG', 'IP', 'WRK', 'DOW',
        'LYB', 'HUN', 'OLN', 'RPM', 'BALL', 'AMCR', 'WLK', 'RGLD', 'MP',
    ],
    'Communication Services': [
        'GOOGL', 'META', 'DIS', 'NFLX', 'CMCSA', 'T', 'VZ', 'TMUS', 'CHTR', 'ATVI',
        'EA', 'TTWO', 'LYV', 'OMC', 'IPG', 'PARA', 'WBD', 'FOX', 'FOXA', 'NWSA',
        'NWS', 'DISH', 'LUMN', 'MTCH', 'ZM', 'SNAP', 'SPOT', 'ROKU', 'YELP',
    ],
}

SYMBOL_TO_SECTOR = {}
for sector, symbols in SECTOR_MAP.items():
    for sym in symbols:
        if sym not in SYMBOL_TO_SECTOR:
            SYMBOL_TO_SECTOR[sym] = sector
